objects:
  red_cylinder_1:
    shape: cylinder
    size: {radius: 0.03, height: 0.06}
    pose: {x: 0.45, y: -0.25, z: 1.03, roll: 0, pitch: 0, yaw: 0}
    color: red

  red_cylinder_2:
    shape: cylinder
    size: {radius: 0.03, height: 0.06}
    pose: {x: 0.52, y: -0.25, z: 1.03, roll: 0, pitch: 0, yaw: 0}
    color: red

  red_cylinder_3:
    shape: cylinder
    size: {radius: 0.03, height: 0.06}
    pose: {x: 0.58, y: -0.25, z: 1.03, roll: 0, pitch: 0, yaw: 0}
    color: red

  red_cylinder_4:
    shape: cylinder
    size: {radius: 0.03, height: 0.06}
    pose: {x: 0.65, y: -0.25, z: 1.03, roll: 0, pitch: 0, yaw: 0}
    color: red

  green_cylinder_1:
    shape: cylinder
    size: {radius: 0.03, height: 0.06}
    pose: {x: 0.45, y: -0.08, z: 1.03, roll: 0, pitch: 0, yaw: 0}
    color: green

  green_cylinder_2:
    shape: cylinder
    size: {radius: 0.03, height: 0.06}
    pose: {x: 0.52, y: -0.08, z: 1.03, roll: 0, pitch: 0, yaw: 0}
    color: green

  green_cylinder_3:
    shape: cylinder
    size: {radius: 0.03, height: 0.06}
    pose: {x: 0.58, y: -0.08, z: 1.03, roll: 0, pitch: 0, yaw: 0}
    color: green

  green_cylinder_4:
    shape: cylinder
    size: {radius: 0.03, height: 0.06}
    pose: {x: 0.65, y: -0.08, z: 1.03, roll: 0, pitch: 0, yaw: 0}
    color: green

  blue_box_1:
    shape: box
    size: {x: 0.05, y: 0.05, z: 0.06}
    pose: {x: 0.45, y: 0.08, z: 1.03, roll: 0, pitch: 0, yaw: 0}
    color: blue

  blue_box_2:
    shape: box
    size: {x: 0.05, y: 0.05, z: 0.06}
    pose: {x: 0.52, y: 0.08, z: 1.03, roll: 0, pitch: 0, yaw: 0}
    color: blue

  blue_box_3:
    shape: box
    size: {x: 0.05, y: 0.05, z: 0.06}
    pose: {x: 0.58, y: 0.08, z: 1.03, roll: 0, pitch: 0, yaw: 0}
    color: blue

  blue_box_4:
    shape: box
    size: {x: 0.05, y: 0.05, z: 0.06}
    pose: {x: 0.65, y: 0.08, z: 1.03, roll: 0, pitch: 0, yaw: 0}
    color: blue

  purple_box_1:
    shape: box
    size: {x: 0.05, y: 0.05, z: 0.06}
    pose: {x: 0.45, y: 0.25, z: 1.03, roll: 0, pitch: 0, yaw: 0}
    color: purple

  purple_box_2:
    shape: box
    size: {x: 0.05, y: 0.05, z: 0.06}
    pose: {x: 0.52, y: 0.25, z: 1.03, roll: 0, pitch: 0, yaw: 0}
    color: purple

  purple_box_3:
    shape: box
    size: {x: 0.05, y: 0.05, z: 0.06}
    pose: {x: 0.58, y: 0.25, z: 1.03, roll: 0, pitch: 0, yaw: 0}
    color: purple

  purple_box_4:
    shape: box
    size: {x: 0.05, y: 0.05, z: 0.06}
    pose: {x: 0.65, y: 0.25, z: 1.03, roll: 0, pitch: 0, yaw: 0}
    color: purple


obstacles:
  shelf1:
    shape: box
    size: {x: 0.75, y: 1.5, z: 0.05}
    pose: {x: -0.80, y: 0.00, z: 0.50, roll: 0, pitch: 0, yaw: 0}

  shelf2:
    shape: box
    size: {x: 0.75, y: 1.5, z: 0.05}
    pose: {x: -0.80, y: 0.00, z: 1.00, roll: 0, pitch: 0, yaw: 0}

  shelf3:
    shape: box
    size: {x: 0.75, y: 1.5, z: 0.05}
    pose: {x: -0.80, y: 0.00, z: 1.50, roll: 0, pitch: 0, yaw: 0}

  shelf4:
    shape: box
    size: {x: 0.75, y: 1.5, z: 0.05}
    pose: {x: -0.80, y: 0.00, z: 2.00, roll: 0, pitch: 0, yaw: 0}

  bookshelf_back:
    shape: box
    size: {x: 0.05, y: 1.5, z: 2.125}
    pose: {x: -1.15, y: 0.00, z: 1.06, roll: 0, pitch: 0, yaw: 0}


targets:
  target1: {x: -1.48, y: -1.35, z: 4.72}
  target2: {x: -1.03, y: -1.35, z: 4.72}
  target3: {x: -0.58, y: -1.35, z: 4.72}
  target4: {x: -0.12, y: -1.35, z: 4.72}
  target5: {x: -1.48, y: -0.45, z: 4.72}
  target6: {x: -1.03, y: -0.45, z: 4.72}
  target7: {x: -0.58, y: -0.45, z: 4.72}
  target8: {x: -0.12, y: -0.45, z: 4.72}
  target9: {x: -1.48, y: 0.45, z: 4.72}
  target10: {x: -1.03, y: 0.45, z: 4.72}
  target11: {x: -0.58, y: 0.45, z: 4.72}
  target12: {x: -0.12, y: 0.45, z: 4.72}
  target13: {x: -1.48, y: 1.35, z: 4.72}
  target14: {x: -1.03, y: 1.35, z: 4.72}
  target15: {x: -0.58, y: 1.35, z: 4.72}
  target16: {x: -0.12, y: 1.35, z: 4.72}


robot:
  pose: {x: 0, y: 0, z: 1.0, roll: 0, pitch: 0, yaw: 0}

