objects:
  red_cylinder_1:
    shape: cylinder
    size: {radius: 0.03, height: 0.06}
    pose: {x: 0.45, y: -0.25, z: 1.03, roll: 0, pitch: 0, yaw: 0}
    color: red

  red_cylinder_2:
    shape: cylinder
    size: {radius: 0.03, height: 0.06}
    pose: {x: 0.52, y: -0.25, z: 1.03, roll: 0, pitch: 0, yaw: 0}
    color: red

  red_cylinder_3:
    shape: cylinder
    size: {radius: 0.03, height: 0.06}
    pose: {x: 0.58, y: -0.25, z: 1.03, roll: 0, pitch: 0, yaw: 0}
    color: red

  red_cylinder_4:
    shape: cylinder
    size: {radius: 0.03, height: 0.06}
    pose: {x: 0.65, y: -0.25, z: 1.03, roll: 0, pitch: 0, yaw: 0}
    color: red

  green_cylinder_1:
    shape: cylinder
    size: {radius: 0.03, height: 0.06}
    pose: {x: 0.45, y: -0.08, z: 1.03, roll: 0, pitch: 0, yaw: 0}
    color: green

  green_cylinder_2:
    shape: cylinder
    size: {radius: 0.03, height: 0.06}
    pose: {x: 0.52, y: -0.08, z: 1.03, roll: 0, pitch: 0, yaw: 0}
    color: green

  green_cylinder_3:
    shape: cylinder
    size: {radius: 0.03, height: 0.06}
    pose: {x: 0.58, y: -0.08, z: 1.03, roll: 0, pitch: 0, yaw: 0}
    color: green

  green_cylinder_4:
    shape: cylinder
    size: {radius: 0.03, height: 0.06}
    pose: {x: 0.65, y: -0.08, z: 1.03, roll: 0, pitch: 0, yaw: 0}
    color: green

  blue_box_1:
    shape: box
    size: {x: 0.05, y: 0.05, z: 0.06}
    pose: {x: 0.45, y: 0.08, z: 1.03, roll: 0, pitch: 0, yaw: 0}
    color: blue

  blue_box_2:
    shape: box
    size: {x: 0.05, y: 0.05, z: 0.06}
    pose: {x: 0.52, y: 0.08, z: 1.03, roll: 0, pitch: 0, yaw: 0}
    color: blue

  blue_box_3:
    shape: box
    size: {x: 0.05, y: 0.05, z: 0.06}
    pose: {x: 0.58, y: 0.08, z: 1.03, roll: 0, pitch: 0, yaw: 0}
    color: blue

  blue_box_4:
    shape: box
    size: {x: 0.05, y: 0.05, z: 0.06}
    pose: {x: 0.65, y: 0.08, z: 1.03, roll: 0, pitch: 0, yaw: 0}
    color: blue

  purple_box_1:
    shape: box
    size: {x: 0.05, y: 0.05, z: 0.06}
    pose: {x: 0.45, y: 0.25, z: 1.03, roll: 0, pitch: 0, yaw: 0}
    color: purple

  purple_box_2:
    shape: box
    size: {x: 0.05, y: 0.05, z: 0.06}
    pose: {x: 0.52, y: 0.25, z: 1.03, roll: 0, pitch: 0, yaw: 0}
    color: purple

  purple_box_3:
    shape: box
    size: {x: 0.05, y: 0.05, z: 0.06}
    pose: {x: 0.58, y: 0.25, z: 1.03, roll: 0, pitch: 0, yaw: 0}
    color: purple

  purple_box_4:
    shape: box
    size: {x: 0.05, y: 0.05, z: 0.06}
    pose: {x: 0.65, y: 0.25, z: 1.03, roll: 0, pitch: 0, yaw: 0}
    color: purple


obstacles:
  bookshelf:
    shape: box
    size: {x: 0.90, y: 1.80, z: 2.55}
    pose: {x: 0.0, y: -0.6, z: 1.27, roll: 0, pitch: 0, yaw: 1.5708}


targets:
  target1: {x: 0.30, y: -1.05, z: 0.69}
  target2: {x: 0.09, y: -0.75, z: 0.69}
  target3: {x: -0.09, y: -0.45, z: 0.69}
  target4: {x: -0.30, y: -0.15, z: 0.69}
  target5: {x: 0.30, y: -1.05, z: 1.29}
  target6: {x: 0.09, y: -0.75, z: 1.29}
  target7: {x: -0.09, y: -0.45, z: 1.29}
  target8: {x: -0.30, y: -0.15, z: 1.29}
  target9: {x: 0.30, y: -1.05, z: 1.89}
  target10: {x: 0.09, y: -0.75, z: 1.89}
  target11: {x: -0.09, y: -0.45, z: 1.89}
  target12: {x: -0.30, y: -0.15, z: 1.89}
  target13: {x: 0.30, y: -1.05, z: 2.49}
  target14: {x: 0.09, y: -0.75, z: 2.49}
  target15: {x: -0.09, y: -0.45, z: 2.49}
  target16: {x: -0.30, y: -0.15, z: 2.49}


robot:
  pose: {x: 0, y: 0, z: 1.0, roll: 0, pitch: 0, yaw: 0}

